<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>登出</description>
   <name>btn_logout</name>
   <tag></tag>
   <elementGuidId>42afe30d-413c-42ea-9bd0-390ea5daf743</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logoutBtn</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
