<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_other</name>
   <tag></tag>
   <elementGuidId>1129b904-aea0-49ad-923f-e69920c7e58e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stepDeposit_depPerson td:last-child button:last-child</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>211114b8-b374-43e9-9dd5-4d0948d636b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d088a24d-73f4-463c-965c-48141bc2a3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default zInput</value>
      <webElementGuid>845dc066-eddf-4a90-9987-1fbd0bfb8343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>其他</value>
      <webElementGuid>37f0f39b-cd62-4170-ba4f-282dedd5951f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepDeposit_depPerson&quot;)/td[@class=&quot;pointBorder&quot;]/button[@class=&quot;btn btn-default zInput&quot;]</value>
      <webElementGuid>c940d5c0-5f87-4557-8a5d-9fe4af7425bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@value=''])[2]</value>
      <webElementGuid>8e4af77a-ba67-4f17-bbdb-b8dafc1dcf81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='stepDeposit_depPerson']/td[2]/button[3]</value>
      <webElementGuid>e16c312d-b9d7-4e5b-a14e-6f91f0a5e2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='物流'])[1]/following::button[1]</value>
      <webElementGuid>e5094f17-b883-4b8d-9796-7ca0cd2d575e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='住戶'])[1]/following::button[2]</value>
      <webElementGuid>6151720c-b9e9-45a4-baf0-bd57e88b948c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='黑貓宅急便'])[1]/preceding::button[1]</value>
      <webElementGuid>57a330b1-b7e4-4904-b64c-bc7d420f36d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='中華郵政'])[1]/preceding::button[2]</value>
      <webElementGuid>4c244009-4488-4715-af45-48836f52cfe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='其他']/parent::*</value>
      <webElementGuid>f20f45d6-30b5-42da-868c-67bf0d0f1c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>adf9ac7e-c41f-44a0-af14-72ed86ea6017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '其他' or . = '其他')]</value>
      <webElementGuid>d2d6928b-07c7-4f19-9af6-23a1607ec708</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
