<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_payment_residents</name>
   <tag></tag>
   <elementGuidId>6c38c5c0-5441-4c06-91c3-53f0c3fa759b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stepDeposit_recPerson td:last-child button:first-child</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[33]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b5d563f-347f-4b94-a03d-d31f12f3d2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>06f286ab-69d3-4f20-bd77-5d3aca5ff974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default zInput</value>
      <webElementGuid>7901f244-39fc-463e-afdb-606f97a0bbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>住戶</value>
      <webElementGuid>b4801f50-45fe-4065-bee8-741306cf294b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepDeposit_recPerson&quot;)/td[@class=&quot;pointBorder&quot;]/button[@class=&quot;btn btn-default zInput&quot;]</value>
      <webElementGuid>f5b543d5-a8ee-4184-af8a-9e7ff522b27b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[33]</value>
      <webElementGuid>b0febc94-9850-4fd5-b43e-799be86ec1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='stepDeposit_recPerson']/td[2]/button</value>
      <webElementGuid>6f3e071d-86c3-470b-bec3-190e3a97e400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::button[1]</value>
      <webElementGuid>194dd99f-fba9-4a0d-b5ac-1727a2b399f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='物流'])[2]/preceding::button[1]</value>
      <webElementGuid>7a0685d8-8761-4007-b8dd-57481769bce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='其他'])[2]/preceding::button[2]</value>
      <webElementGuid>9f618c0a-9399-424a-ba31-b77ed8ac5436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/button</value>
      <webElementGuid>06df1d1b-bb50-4d46-afa7-4407c31bd914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '住戶' or . = '住戶')]</value>
      <webElementGuid>6e5c7f7b-7f4c-4874-a223-c870e49bf232</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
