<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>floor</name>
   <tag></tag>
   <elementGuidId>b127fe0b-0098-4f4c-bc00-6b4eb6f22b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Floor0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selFloor_m']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7c1c664e-7144-424e-b30f-e565d98d0a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selFloor_m</value>
      <webElementGuid>4dbd123d-4c5a-47dc-bba9-1bd62bb05c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>79bc031c-5bb3-41b4-bb23-19e3dac05b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selTabletElement.FloorClick()</value>
      <webElementGuid>f6310549-8357-4ae4-891e-0ba3f750e68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>第 1 樓第 2 樓第 3 樓</value>
      <webElementGuid>11c5d5ae-19b2-4199-81a2-916a7678f573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selFloor_m&quot;)</value>
      <webElementGuid>20bda6b1-6abf-4557-b1bf-deb9789ecdbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selFloor_m']</value>
      <webElementGuid>1dc1fb83-2462-4240-8d58-54bc5ff31423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='masterTabletDiv']/div[2]/table/tbody/tr/td[3]/select</value>
      <webElementGuid>5a38d8f9-c8c9-4ff5-8fd1-4bfea3d26bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='請選擇住戶資訊(棟別、樓層、戶別)'])[2]/following::select[2]</value>
      <webElementGuid>c57e598e-b4d0-4c76-b0ca-cdaa7659ef2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='確認'])[1]/following::select[2]</value>
      <webElementGuid>71b8212f-ee93-4493-bff8-45ff1e7eeba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='影像紀錄'])[1]/preceding::select[3]</value>
      <webElementGuid>d1d7f649-7f87-4984-ba43-0fb64ebda47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div[2]/table/tbody/tr/td[3]/select</value>
      <webElementGuid>2a65e737-7207-4a3a-89fa-b66fb126144f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selFloor_m' and (text() = '第 1 樓第 2 樓第 3 樓' or . = '第 1 樓第 2 樓第 3 樓')]</value>
      <webElementGuid>8e47b943-8a5d-4f8a-b5af-f41aab8e00e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
