<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Deposit_surName</name>
   <tag></tag>
   <elementGuidId>a71f26f8-9d48-42c7-a3a1-1193c38b9447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputDeposit_selName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputDeposit_selName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62b869f5-1072-4ed9-b268-9997d5c1fd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputDeposit_selName</value>
      <webElementGuid>10daeed5-d806-4def-8940-f4b65e712501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>deb6946d-c609-469b-a0b9-eef4a3e72168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control PersonName</value>
      <webElementGuid>aa903617-5176-476a-9731-a8a69be8fe27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5308f297-5b02-4a10-8b39-b9b1ffc76b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>aea74a85-f58d-4897-8d1a-fa15e280a47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>請輸入寄放人姓名...</value>
      <webElementGuid>f8e56d0c-a702-481e-97bc-10f0780f65e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputDeposit_selName&quot;)</value>
      <webElementGuid>4d9f7267-6bb8-4613-90dd-0734f45ca14c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputDeposit_selName']</value>
      <webElementGuid>8363f80a-1df8-4406-bf01-0c9c279f9ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='stepDeposit_depPersonName']/td[2]/input</value>
      <webElementGuid>69cd9510-f586-4efa-ae76-6183cc921b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>f5e65549-641d-4d34-a1f2-e93d6458988e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputDeposit_selName' and @type = 'text' and @placeholder = '請輸入寄放人姓名...']</value>
      <webElementGuid>6cb10875-131d-45ed-a338-326c7daed7e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
