<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_residents_name</name>
   <tag></tag>
   <elementGuidId>98853917-8763-44be-858e-3eb676995a8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='stepDeposit_recPersonName']/td[2]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#stepDeposit_recPersonName > td:nth-of-type(2) > select.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>525eb30b-4f42-479d-a3e8-79bf221d8705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>50afe5dd-2564-4e81-ae28-69cd8d8c13eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>請選擇Nc AutoTestWolf自動化yuhsinAuto全戶通知</value>
      <webElementGuid>e9406605-b366-4b4e-b4f1-43ce0377457b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepDeposit_recPersonName&quot;)/td[2]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>59b08102-9e4c-4505-998f-9c8817abe8bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='stepDeposit_recPersonName']/td[2]/select</value>
      <webElementGuid>cdd2a10d-50f8-46b9-9b72-29c8911e8698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='領取人姓名'])[1]/following::select[1]</value>
      <webElementGuid>d87e085b-d46a-44ad-9399-00341cb9cf5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='其它'])[2]/following::select[1]</value>
      <webElementGuid>dfd10bbf-c15e-4429-964b-4fda713e2ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提示_'])[2]/preceding::select[1]</value>
      <webElementGuid>3d3d618e-ce14-4e56-b0ac-dec427357ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='選擇領取人'])[1]/preceding::select[1]</value>
      <webElementGuid>54a40dcf-0dfc-4f54-9ceb-199850742de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[3]/td[2]/select</value>
      <webElementGuid>e66227fc-b422-46f7-ab90-9ec3c54324ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '請選擇Nc AutoTestWolf自動化yuhsinAuto全戶通知' or . = '請選擇Nc AutoTestWolf自動化yuhsinAuto全戶通知')]</value>
      <webElementGuid>3529727e-a09f-43c3-9d4f-0404c20d6aa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
