<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_type-cgy</name>
   <tag></tag>
   <elementGuidId>390fc3e6-1a13-444c-9bbf-742815c25f86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paymentTBody tr td:nth-of-type(2) .form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='paymentTBody']/tr/td[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8cc2b612-f4ad-4e16-abe1-7350a8fcb92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>29c11c8b-4b38-43be-b42b-1a79fcdcab0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>請選擇現金非現金</value>
      <webElementGuid>7ad7ce0a-772e-431d-86c1-10295f63ea72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentTBody&quot;)/tr[1]/td[@class=&quot;type-cgy&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>aebbe3d0-97e9-4c50-be8e-cb8dbd0af969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='paymentTBody']/tr/td[2]/select</value>
      <webElementGuid>5c8c63a3-e06e-444f-88c6-b5279727fcdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B61'])[1]/following::select[1]</value>
      <webElementGuid>e4c75c5b-580f-4fd9-9968-5fdd339e3b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='操作'])[1]/following::select[1]</value>
      <webElementGuid>3c6dcefc-2ab4-4a20-8aae-6fa0b8539d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='冷藏'])[1]/preceding::select[2]</value>
      <webElementGuid>6cceafbe-0a10-4a80-998a-8e48a0c95bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='冷凍'])[1]/preceding::select[2]</value>
      <webElementGuid>20a8e22a-d13f-407d-8516-e2cd054ec924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[2]/select</value>
      <webElementGuid>75bed170-9a30-4e7a-9aa2-d77f64050b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '請選擇現金非現金' or . = '請選擇現金非現金')]</value>
      <webElementGuid>2ac6d1b3-6adf-4765-8874-f386d3cadcd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
