<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tablet_note</name>
   <tag></tag>
   <elementGuidId>7f5eeb65-b864-456e-9501-20a46e10fb49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#masterTabletDiv #selTablet_m</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selTablet_m']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0522749e-4f1c-4e58-ad4c-490c6a69e19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selTablet_m</value>
      <webElementGuid>4ecb41a9-ea48-40d7-baea-562ab3e8572b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>f1a733d5-44d7-4c57-8d15-9eb4b505f479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selTabletElement.TabletClick()</value>
      <webElementGuid>d47275b0-3d25-4eda-8aec-5d16c9d7ac65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A1F2A2F2A3F2</value>
      <webElementGuid>c5b3a6f8-468c-4e3b-95b5-92892e3e56d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selTablet_m&quot;)</value>
      <webElementGuid>8512efc1-a111-4fae-96b9-e5d4f2a3187e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selTablet_m']</value>
      <webElementGuid>bbb6284b-bd76-4bfd-9403-251e69f3e784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='masterTabletDiv']/div[2]/table/tbody/tr/td[5]/select</value>
      <webElementGuid>64e00696-1ffc-4435-ae1f-7d0cdcdeae04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='請選擇住戶資訊(棟別、樓層、戶別)'])[2]/following::select[3]</value>
      <webElementGuid>c01a3abb-b6d0-4766-a396-10c33c29ac0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='確認'])[1]/following::select[3]</value>
      <webElementGuid>d5e57b24-6ca5-49c5-987f-0f955aff9d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='影像紀錄'])[1]/preceding::select[2]</value>
      <webElementGuid>2cad2547-7dfe-4354-9fad-12b0a3eb0cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div[2]/table/tbody/tr/td[5]/select</value>
      <webElementGuid>59682cfe-0a49-425f-b78d-ccd070c3a039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selTablet_m' and (text() = 'A1F2A2F2A3F2' or . = 'A1F2A2F2A3F2')]</value>
      <webElementGuid>d1d61b2e-9b5b-42fb-918a-e39b7c71bf4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
