<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tag</name>
   <tag></tag>
   <elementGuidId>34b4a8f8-59da-46cd-84b0-55d1b737aae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Building0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selTag_m']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0cdcfb51-3bcd-4b67-8d02-04325a4950a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>0f180981-b12c-4318-90f7-f7842e0b68fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selTag_m</value>
      <webElementGuid>b1e2d0fb-07d0-4a71-828a-7133baac6acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selTabletElement.TagClick()</value>
      <webElementGuid>07c45ec7-0c90-4bb0-93b1-bb6ec0478559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABC</value>
      <webElementGuid>bbe4cd73-7944-4aec-93ff-5d0130ac6678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selTag_m&quot;)</value>
      <webElementGuid>b43f3ff8-09a8-435c-9314-7f06511eaf8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selTag_m']</value>
      <webElementGuid>143aa2a0-3bad-414f-9324-2cedeb25f378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='masterTabletDiv']/div[2]/table/tbody/tr/td/select</value>
      <webElementGuid>2779d45e-1fc1-4b55-99c3-a51303c0647d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='請選擇住戶資訊(棟別、樓層、戶別)'])[2]/following::select[1]</value>
      <webElementGuid>f132b09f-f01b-44f1-a883-aff73ce216d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='確認'])[1]/following::select[1]</value>
      <webElementGuid>45e2c615-1fd5-48bb-b2cc-877d9b45b085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='影像紀錄'])[1]/preceding::select[4]</value>
      <webElementGuid>4a3123cb-adb5-4bc7-a45e-71f2d1879770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div[2]/table/tbody/tr/td/select</value>
      <webElementGuid>e0f011e0-1472-4282-a2c7-fa01c126befa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selTag_m' and (text() = 'ABC' or . = 'ABC')]</value>
      <webElementGuid>0e1c8135-c270-4887-bc02-a757e591f80c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
