<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>領取結單</description>
   <name>span_Receive</name>
   <tag></tag>
   <elementGuidId>d77d3f1a-a325-4fdd-a69f-c2826b49ba16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#theEnd</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
