<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>floor</name>
   <tag></tag>
   <elementGuidId>296fef09-37c6-4dce-9fb0-a99b59add1a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Floor1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selFloor_m']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4fcea73d-3a25-4e80-bbd3-269b52009e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selFloor_m</value>
      <webElementGuid>712df863-a3f0-4938-848d-832ac0e8a8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>1fd503fa-35be-4cf3-bd02-facfef6c54b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selTabletElement.FloorClick()</value>
      <webElementGuid>432a7b5d-cdbb-4056-8141-e29cd0e50c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>第 1 樓第 2 樓第 3 樓</value>
      <webElementGuid>ff6e459a-f547-4dc2-b9f1-ab5a5b336473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selFloor_m&quot;)</value>
      <webElementGuid>64fd5c50-a01a-466b-9c34-b8d93aaeefb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selFloor_m']</value>
      <webElementGuid>d98a0f14-93e1-4e2e-98ad-39ceb81d169d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='masterTabletDiv']/div[2]/table/tbody/tr/td[3]/select</value>
      <webElementGuid>c052ad99-807e-4909-a453-edcfa0e5ccad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='請選擇住戶資訊(棟別、樓層、戶別)'])[2]/following::select[2]</value>
      <webElementGuid>91a7eec1-09f7-425a-8588-ac5b6a75e7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='確認'])[1]/following::select[2]</value>
      <webElementGuid>2e9df566-f767-49d0-a463-72b7a9e71c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='影像紀錄'])[1]/preceding::select[3]</value>
      <webElementGuid>5a0163f9-c3dc-4e54-9d1b-2e990c872569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div[2]/table/tbody/tr/td[3]/select</value>
      <webElementGuid>36af6902-96d0-421f-bae2-e4926c4ae444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selFloor_m' and (text() = '第 1 樓第 2 樓第 3 樓' or . = '第 1 樓第 2 樓第 3 樓')]</value>
      <webElementGuid>9c289fe0-cc8d-4160-b1a1-e869774de192</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
