<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Notify_residents</name>
   <tag></tag>
   <elementGuidId>8a559b2c-b528-4d13-b31f-3f721b780916</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='oneClick']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#oneClick</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13a095f5-3a41-458e-843b-248d2d4d1e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40c2ce6e-4b38-4422-8878-e3de4b921797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oneClick</value>
      <webElementGuid>328b0412-b689-4aef-8318-e9c8b66ce5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>summit btn btn-md btn-primary pointBorderEx</value>
      <webElementGuid>e9d00751-d0d3-4cf2-9fb4-47f0bbf4879f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading-text</name>
      <type>Main</type>
      <value>通知中...</value>
      <webElementGuid>7655da1a-8749-49a3-bc40-faeafc0c1819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>通知住戶提示_點選【通知住戶】就完成囉！</value>
      <webElementGuid>d700c994-2cb8-4a55-9e6d-bfc8a21a8986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oneClick&quot;)</value>
      <webElementGuid>7e47e417-aeee-41f7-ba15-dbf5bd3df117</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='oneClick']</value>
      <webElementGuid>08b9ab78-8d41-4b2c-a851-595d00ddf061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[4]/div[2]/div/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>4091ec9e-8cd8-4c1c-99fc-79d61870bf0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新增'])[1]/following::button[1]</value>
      <webElementGuid>dc296ef8-fc07-4021-804c-edc07a553dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='複製'])[2]/following::button[2]</value>
      <webElementGuid>1d98e00a-e00e-403e-8af9-02a09e3b9fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='通知住戶']/parent::*</value>
      <webElementGuid>f87bc710-357a-4b74-a5e8-c1aa506c1044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>77e29b01-5203-4cd6-8889-e823bf25aa33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'oneClick' and (text() = '通知住戶提示_點選【通知住戶】就完成囉！' or . = '通知住戶提示_點選【通知住戶】就完成囉！')]</value>
      <webElementGuid>7b6a97a8-72fb-42cb-bd10-3d157ce0369c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
