<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tablet_note</name>
   <tag></tag>
   <elementGuidId>c8020105-11e0-4f15-bc42-7e34bf32ad93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selTablet_m']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#masterTabletDiv #selTablet_m</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1f65aac0-5b05-4fa1-bca4-55c30ad24e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selTablet_m</value>
      <webElementGuid>25c46432-ec7a-467a-8fb9-9f7ccfe050b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>f82605eb-83c8-41f2-9043-40f18cf90988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selTabletElement.TabletClick()</value>
      <webElementGuid>548ffbc5-c4cf-406e-b9e2-d61aa0275d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A1F2A2F2A3F2</value>
      <webElementGuid>c3f5955d-ec6c-4f61-a3e0-9f4016db30ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selTablet_m&quot;)</value>
      <webElementGuid>652e046b-7317-43e0-93f6-8df52ebd49c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selTablet_m']</value>
      <webElementGuid>c1c9c0b4-1c13-4cd4-b5f7-b569a0f08525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='masterTabletDiv']/div[2]/table/tbody/tr/td[5]/select</value>
      <webElementGuid>aa713140-cf94-4c7c-9f82-7cbb9dd21b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='請選擇住戶資訊(棟別、樓層、戶別)'])[2]/following::select[3]</value>
      <webElementGuid>179c84ad-3dbe-4805-a98c-11b8b3219ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='確認'])[1]/following::select[3]</value>
      <webElementGuid>2803f7e4-a826-41a4-8f6e-bea548101925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='影像紀錄'])[1]/preceding::select[2]</value>
      <webElementGuid>0895771e-6ec8-48d6-aab2-a82aa7fbdaac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div[2]/table/tbody/tr/td[5]/select</value>
      <webElementGuid>f63ac87f-7558-4dd7-934b-ccf1d957afda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selTablet_m' and (text() = 'A1F2A2F2A3F2' or . = 'A1F2A2F2A3F2')]</value>
      <webElementGuid>0417238a-d945-4817-9873-0eda6485e5fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
