<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>信件包裹領取-郵件/包裹列表</description>
   <name>element_title</name>
   <tag></tag>
   <elementGuidId>28411236-e308-44c0-8c74-4c05b3891449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postalReceiveNote</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
