<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>快速領取</description>
   <name>btn_quick_receive</name>
   <tag></tag>
   <elementGuidId>17cd4719-7ad1-423e-adbe-953e5ea45f12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.fab-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
