<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>備註</description>
   <name>title_list</name>
   <tag></tag>
   <elementGuidId>bf86ea09-da7a-44ba-8a6f-97291fd93117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#step3ReceiveNote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
