<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LoginInfo</name>
   <tag></tag>
   <elementGuidId>31c66bb8-4c4d-4f24-96fd-711c9049662a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.loginInfro</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
