<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>access_card</name>
   <tag></tag>
   <elementGuidId>286b3e8d-3acf-4f9b-ad0a-0028eac6784e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='methodSelDialog']/div/div[2]/div/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.way-select > ul > li:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6afc8339-49e9-4f2c-a034-d5ba42db3471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>手機條碼</value>
      <webElementGuid>2b0bcc28-c626-458a-8fb6-3eee98d29a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;methodSelDialog&quot;)/div[@class=&quot;el-dialog el-dialog--center&quot;]/div[@class=&quot;el-dialog__body&quot;]/div[@class=&quot;way-select&quot;]/ul[1]/li[1]</value>
      <webElementGuid>81ce5f26-3b40-4c1a-a8d0-8af5fa285836</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='methodSelDialog']/div/div[2]/div/ul/li</value>
      <webElementGuid>0126d33d-a87c-4e05-a327-651bb10b07c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='請選擇驗證方式'])[1]/following::li[1]</value>
      <webElementGuid>a53faa22-1183-4642-9712-6683a273e6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='領取'])[2]/following::li[1]</value>
      <webElementGuid>e3bdc4da-e65d-4837-88a7-494f0dd14443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='門禁卡、磁扣'])[1]/preceding::li[1]</value>
      <webElementGuid>8f03634a-a8ac-45c9-b493-439f12b1abb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/ul/li</value>
      <webElementGuid>74a6474f-2b3d-4123-8c79-ed1d50c0f6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '手機條碼' or . = '手機條碼')]</value>
      <webElementGuid>9a894491-a5b0-4817-b97c-5af3338f7455</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
