<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>success</name>
   <tag></tag>
   <elementGuidId>fd6c8177-1d80-48a1-a40a-52272e9b10b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='postal-content']/div/div[2]/a/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wizardContent3 #totalGet</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2f8579d8-4eb0-42ad-960d-95ee077d390a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon icon-p-receive</value>
      <webElementGuid>e91a7c32-6aa7-49a8-81cc-ecf08d99f8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@click</name>
      <type>Main</type>
      <value>clickPostalThumbnail('領取')</value>
      <webElementGuid>d230c8d6-bf97-419c-85b7-ad56f1bb22a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postal-content&quot;)/div[@class=&quot;row text-center&quot;]/div[@class=&quot;col-md-3 col-sm-6&quot;]/a[1]/div[@class=&quot;thumbnail&quot;]/i[@class=&quot;glyphicon icon-p-receive&quot;]</value>
      <webElementGuid>2d0ad75c-a5c9-4400-b45b-853e2aa131bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='postal-content']/div/div[2]/a/div/i</value>
      <webElementGuid>47bee47e-316f-4259-9c58-33078944c503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/i</value>
      <webElementGuid>9288d113-f6a5-4eb4-ad72-b6070a9317cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
