<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BarcodeToken</name>
   <tag></tag>
   <elementGuidId>610876c1-c480-4ea1-816d-d60ce2df9e57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fastMobile_code</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
