<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CardToken</name>
   <tag></tag>
   <elementGuidId>eccb1354-27ba-4c90-86c8-e45c80721967</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fastCarrier_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
