<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>確認送出</description>
   <name>btn_send</name>
   <tag></tag>
   <elementGuidId>db6d7d65-7d81-4feb-9d40-5873fe2c8bb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#send</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div[2]/input[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
