<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>announcement_edit</name>
   <tag></tag>
   <elementGuidId>32e15ef5-739c-45a4-a676-1de44b98120c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.el-table__body-wrapper.is-scrolling-none .el-button.el-button--default.el-button--mini.is-plain</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='news_main']/div/div[4]/div[3]/table/tbody/tr/td[10]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cc328a72-eb02-4480-8968-b4a4c56f86bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mgmt/news/newsEdit?id=2407090896</value>
      <webElementGuid>91d2ea64-ece5-4c7e-96e0-52ca6fd39103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button el-button--default el-button--mini is-plain</value>
      <webElementGuid>aa197e4f-ee94-4a75-90fe-d5f492a8b218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            編輯
          </value>
      <webElementGuid>29bb8b6f-7bfe-470a-842a-d9eccf7af20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;news_main&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;el-table newslist el-table--fit el-table--enable-row-hover el-table--enable-row-transition&quot;]/div[@class=&quot;el-table__body-wrapper is-scrolling-none&quot;]/table[@class=&quot;el-table__body&quot;]/tbody[1]/tr[@class=&quot;el-table__row&quot;]/td[@class=&quot;el-table_1_column_10   el-table__cell&quot;]/div[@class=&quot;cell&quot;]/a[@class=&quot;el-button el-button--default el-button--mini is-plain&quot;]</value>
      <webElementGuid>a0086b9b-24fd-40b1-b14e-ed73b0dbd3c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='news_main']/div/div[4]/div[3]/table/tbody/tr/td[10]/div/a</value>
      <webElementGuid>5f2333f8-6e56-4af7-9da5-63f3e85bca4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'編輯')]</value>
      <webElementGuid>e42f889c-bd03-4f0c-9964-00861d389c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='刊登中'])[2]/following::a[1]</value>
      <webElementGuid>13dc617d-154c-425c-8cd0-d2704d5bf52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='管理辦法'])[2]/following::a[1]</value>
      <webElementGuid>6a1e0b91-1fe9-4a17-bc79-8b3dc280e84c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='刪除'])[1]/preceding::a[1]</value>
      <webElementGuid>c9f467b7-1d9b-4946-9c72-362f8638fe8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新增一下來自物業雲的公告'])[1]/preceding::a[1]</value>
      <webElementGuid>cb51fb2b-0ced-40f8-8da8-62003b10b816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='編輯']/parent::*</value>
      <webElementGuid>773a0ebd-1431-436c-9243-fd24ec45000a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mgmt/news/newsEdit?id=2407090896')]</value>
      <webElementGuid>ad1fc432-b7d0-40c4-82a7-87cad60787f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/a</value>
      <webElementGuid>13a01e7b-07dc-4ccb-b276-4fc6a64b9eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mgmt/news/newsEdit?id=2407090896' and (text() = '
            編輯
          ' or . = '
            編輯
          ')]</value>
      <webElementGuid>c69cb7a7-2b5d-42bf-a4cc-166cd97569a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
