<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IsSignature_receive_end</name>
   <tag></tag>
   <elementGuidId>2b75141e-b684-4f7f-a27b-c7db3695f67f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.el-dialog.is-fullscreen.el-dialog--center .el-dialog__footer .el-button.el-button--primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[48]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc7ae04e-9d51-4efb-8a22-14b16b3d976a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>933581ae-92ed-41c2-baca-0899f0883950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-md btn-default cancelBtn</value>
      <webElementGuid>f0fe1bb2-1c1e-4120-9e80-088fcbb4b335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return fo._dialogClose('bindCard_div')</value>
      <webElementGuid>389f5712-4cab-4998-aa98-edc041750301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>取消</value>
      <webElementGuid>faec83ae-9510-457b-9bf6-a49e32f197ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bindCard_div&quot;)/button[@class=&quot;btn btn-md btn-default cancelBtn&quot;]</value>
      <webElementGuid>2b1ef022-f935-41c1-8939-9776ad0cd308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[48]</value>
      <webElementGuid>a7152aec-0a75-4282-be17-5b5799677357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bindCard_div']/button[2]</value>
      <webElementGuid>1037a04c-7295-46ca-8ed1-cb260afdc7db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='請感應門禁卡...'])[2]/following::button[1]</value>
      <webElementGuid>07039ae8-49c1-4338-aa59-03a280b37fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='確定'])[3]/following::button[2]</value>
      <webElementGuid>1448e3f5-bb36-4781-b9c6-c7da1344925f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='告警管理'])[1]/preceding::button[2]</value>
      <webElementGuid>5111a6bc-7e86-4c01-9fea-c04194b5a112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='隱藏'])[1]/preceding::button[2]</value>
      <webElementGuid>52787068-d95c-4f5d-87fb-d4d43e98d429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[43]/button[2]</value>
      <webElementGuid>827c8881-d761-4eb6-8738-bceae18d4e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '取消' or . = '取消')]</value>
      <webElementGuid>c6f7fdf4-891a-42b0-b744-ab435bac949e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
