<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IsSignature_access_card</name>
   <tag></tag>
   <elementGuidId>07d69d18-cf98-4d06-b842-e232fce991e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='methodSelDialog']/div/div[2]/div/ul/li[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;新增載具&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>90a8f91f-7a26-4646-9a7b-c9decde8489d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.kingnetsmart.com.tw/Sites/housekeeper-web-mgmt/86805/html/img/nfc.eab5644f.png</value>
      <webElementGuid>5769acdb-d65b-4cb8-b297-a6a7ca4dc9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>新增載具</value>
      <webElementGuid>71bd6b9b-2b17-413f-91b3-39efe835cc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;methodSelDialog&quot;)/div[@class=&quot;el-dialog el-dialog--center&quot;]/div[@class=&quot;el-dialog__body&quot;]/div[@class=&quot;way-select&quot;]/ul[1]/li[2]/img[1]</value>
      <webElementGuid>8fc7a6a7-bf74-46ae-8c39-5fb09178c904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='methodSelDialog']/div/div[2]/div/ul/li[2]/img</value>
      <webElementGuid>b5f5bc83-7991-46d6-a76d-335057039b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='新增載具']</value>
      <webElementGuid>7c28bfa9-b3cc-4bf4-9134-948af7de7f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/img</value>
      <webElementGuid>f58e342e-65a2-4dc2-8cb7-d179ca10ac0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.kingnetsmart.com.tw/Sites/housekeeper-web-mgmt/86805/html/img/nfc.eab5644f.png' and @alt = '新增載具']</value>
      <webElementGuid>738083e0-9f7c-4cfb-a581-c1342387dba0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
