<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Step3.確認細項-確認送出</description>
   <name>btn_send</name>
   <tag></tag>
   <elementGuidId>29ba22ff-ff6b-4f7b-9108-0626d5d9cf4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#send</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
