<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_token</name>
   <tag></tag>
   <elementGuidId>d5546389-9369-4b81-a1a9-1c998e13b445</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_code</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
